# **1. Edge Detection**

Edge detection is one of the common practices in computer vision which is the idea of detecting edges of different objects in image which has several applications like image segmentation, feature extraction, and other. Edge detection works by giving higher intesity to edges and supressing other values to the background.

## **1.1 Laplacian Image Gradient For Edge Detection**

The Laplacian image gradient is a popular technique in image processing and computer vision that is famously used for edge detection. It uses the Laplacian Operator to find the edges.

The basic assumption is that the edges of a particular object in an image will strictly increase or decrease their intensity suddenly. Therefore, if we can differentiate the rate of change of the intensity of pixel values based on the space they are in the image, we can detect edges. However, for further improvement, we can use the second derivative of the image. Here we calculate how the rate of change of pixels changes according to the space they are in. This will give us higher values when we are at the boundaries of an object in the pixel, which helps to detect edges.

For applying laplacian operator on an image, we convolve the image with a laplacian kernel, which is a small matrix representing the descrete approximation of laplacian operator.

After performing convolution witht the laplacian kernel, we obtain a new image where the edges are enhanced and the backgorund noise is suppressed.

In [1]:
import cv2 as cv
import numpy as np

img = cv.imread('D:/OpenCV2/Assets/sudoku_paper.png', cv.IMREAD_GRAYSCALE)
img2 = cv.Laplacian(img.copy(), ddepth=64)
cv.imshow('window', np.hstack([img, img2]))

cv.waitKey(0)
cv.destroyAllWindows()

## **1.2 Canny Edge Detection**

Canny Edge detection is one of the best and popular edge detection algorithm introduced by John F. Canny. It goes through several steps to finally obtain the image where the edges are perfectly marked. 

Here are the steps involved in Canny Edge Detection. 

1. **Convert the Image to Grayscale.**
2. **Apply Gaussian blur.**
3. **Apply Sobel Operator.**
4. **Apply non-maximum supression.**
5. **Apply Thresholding.**
6. **Edge Tracking by histerisis.**

Edge detection algorithms, specifically Canny Edge Detection, work under the assumption that high changes in intensity within an image indicate the presence of an edge. By calculating the **gradient** of a pixel in relation to its neighboring pixels both horizontally and vertically (Applying Sobel Operator), we can identify these sudden changes and accurately detect edges in the image.

### **1.2.1 Converting the image to gray scale**

Converting the image to grayscale before applying canny edge detection can be beneficial since grayscale images deal with two intensities, either high or low. This makes the process easier. Converting the image to gray scale can be simply done with opencv.

In [16]:
img = cv.imread('D:/OpenCV2/Assets/newton.jpg')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('window', gray)
cv.waitKey(0)
cv.destroyAllWindows()

### **1.2.2 Applying Gaussian Blur**

Gaussian blur is a technique used to normalize images and produce a blur effect that smoothens the image. But why do we need to apply it? 

When we consider a raw image, the edges and other parts might be very sharp and clear, which can lead to sudden intensity changes and affect edge detection. For example, when there are two edges close to each other, if we don't apply Gaussian blur before thresholding, the higher intensity edges will remove the lower intensity edges, which reduces the accuracy of edge detection. 

Therefore, applying Gaussian blur is a common approach before any edge detection task to ensure accurate and reliable results.

In [9]:
img = cv.imread('D:/OpenCV2/Assets/sudoku_paper.png')
blurred = cv.GaussianBlur(img, (5, 5), 0)
cv.imshow('window', blurred)
cv.waitKey(0)
cv.destroyAllWindows()

### **1.2.3 Applying Sobel Operator**

The Sobel Operator is a type of edge detection technique that detects edges by examining each pixel of an image and its horizontal and vertical neighboring pixels. It is essentially a 3x3 kernel that can be applied to an image to produce a gradient vector containing the values of intensity changes of pixels with respect to their neighboring pixels. 

Here's how it works:

1. First, each individual pixel is examined one by one.
2. For each pixel, we calculate the rate of change of that pixel with respect to its neighboring pixels both horizontally and vertically. This can be done by finding the derivatives of horizontal and vertical pixel changes with respect to the current pixel.
3. After applying the kernel (Sobel Operator), we get a gradient vector.
4. This gradient vector contains the rate of change in both horizontal and vertical directions.
5. Finding the magnitude of this vector will give us information about the overall intensity of the current pixel with respect to its neighbors.
6. The orientation/direction of this vector will give us information about where the intensity is increasing mostly, either in the horizontal direction or the vertical direction.
7. Finally, we use the computed magnitude and plug it as the current pixel value. We'll place this value in the same pixel index or position of the new edge-detected image that we are going to create.

Here are the Sobel kernels:

Horizontal Sobel kernel:

\begin{bmatrix}
-1 & 0 & 1 \\
-2 & 0 & 2 \\
-1 & 0 & 1
\end{bmatrix}

Vertical Sobel kernel:

\begin{bmatrix}
-1 & -2 & -1 \\
0 & 0 & 0 \\
1 & 2 & 1
\end{bmatrix}

After applying both of this for each of 3x3 window of an image, we'll get the gradient vector, Suppose, we got the gradient vector of a single pixel like this,

\begin{bmatrix}
55 \\
45
\end{bmatrix}

To find the magnitude, you can use the Pythagores Theorem.

$$
\text{Magnitude} = \sqrt{{\text{Horizontal\_Gradient}}^2 + {\text{Vertical\_Gradient}}^2}
$$

$$
\text{Magnitude} = \sqrt{{\text{55}^2 + {\text{45}^2}}} = 71.064
$$

We can round this magintude and apply to the new image same pixel position as of the original image.
Doing this for each of the pixels will give us a new image which consists of detected edges.

For finding the orientation, we can use the **arctan** of the ration between horizontal and vertical rate of change values in the gradient vector. 

Arctan is just the inverse of tangent function, we are performing arctan because we are interested in finding the angle between these two values, based on that angle, we can find the orientation of the gradient vector. Well, we know that,

$$
\tan(\theta) = \frac{\text{adjacent}}{\text{opposite}}
$$

So if we have the values similar to adjacent and opposite side which is horizontal and vertical rate of change values, we could do,

$$
\text{arctan}\left(\frac{\text{opposite}}{\text{adjacent}}\right) = \theta
$$



In [17]:
gradient_x = cv.Sobel(src=blurred, ddepth=cv.CV_64F, dx=1, dy=0, ksize = 3)
gradient_y = cv.Sobel(blurred, cv.CV_64F, dx=0, dy=1, ksize=3)


print(gradient_x)
print(gradient_y)

[[[   0.    0.    0.]
  [  -8.   -8.   -8.]
  [ -24.  -24.  -24.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [ -15.  -15.  -15.]
  [ -42.  -42.  -42.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [ -31.  -31.  -31.]
  [ -83.  -83.  -83.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 ...

 [[   0.    0.    0.]
  [-128. -128. -128.]
  [-357. -357. -357.]
  ...
  [   4.    4.    4.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [-128. -128. -128.]
  [-359. -359. -359.]
  ...
  [   4.    4.    4.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[   0.    0.    0.]
  [-128. -128. -128.]
  [-360. -360. -360.]
  ...
  [   4.    4.    4.]
  [   0.    0.    0.]
  [   0.    0.    0.]]]
[[[   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]
  ...
  [   0.    0.    0.]
  [   0.    0.    0.]
  [   0.    0.    0.]]

 [[  -2.   -2.

### **1.2.4 Non-Maximum Supression**

The Sobel Operator is a commonly used method to find edges in an image, but it has a limitation. The resulting image may contain thick and dispersed edges since Sobel does not consider the thickness of the edges. To address this issue, we can apply non-maximum suppression to the resulting image obtained after applying the Sobel operator.

Non-maximum suppression works by suppressing pixel values that have lower intensity than the global maximum intensity values. In other words, intensities that are lower than the maximum intensity of the image are converted to zero. The global maximum intensity represents where the edges are located, so removing the remaining intensities makes sense.

This process involves examining neighboring intensities and the direction in which they are increasing or decreasing. Based on this information, we can determine which pixel intensities to suppress and which ones to keep.

### **1.2.5 Thresholding**

In this step, we choose a threshold value to adjust the brightness of certain pixels in an image. The pixels on the edges of the image need to be brighter while the others need to be dimmer. This is because the values of the pixels on the edges are usually greater than the values of the other pixels. By applying thresholding, we can enhance the edges of the image based on a specific threshold value.

### **1.2.6 Edge Tracking by histerisis**

This is the last and final step which involves tracking the edges. This step if optional but is preferd since it will give more clarity to edges. The idea behind edge tracking by hysteresis is to link adjacent edge pixels to form continuous edges and suppress isolated edge pixels that may be noise.

The process begins by classifying the edges into three categories based on their gradient magnitude:

* Strong Edges: Pixels with gradient magnitudes above a high threshold.
* Weak Edges: Pixels with gradient magnitudes between a low and high threshold.
* Non-Edges: Pixels with gradient magnitudes below a low threshold.

In [18]:
edges = cv.Canny(img, threshold1=50, threshold2=100)

cv.imshow('window', edges)
cv.waitKey(0)
cv.destroyAllWindows()