# **1. Thresholding**

Threhsolding is a simple yet powerful technique used in computer vision for segmenting or seperating specific parts of an image based on a threhold. It is commonly applied on grayscale images and the idea is to convert a grayscale or color image to binary image based on a threshold, where each pixel is classified as either in the foreground or in the background.

Thresholding can be useful in many case, some of the include:

* **Segmenting**: It can be used for segmenting some part of the image which is important, for example we can segment cancer cells from a image that contains the organs where cancer is attacked.
* **Object Detection**: Thresholding plays an important role in object detection, where we can detect an object based on its appearance in the foreground or background, specific threshold values can be used for detecting object in new images by training a model to understand which threshold.


## **1.1 Simple Binary Thresholding**

In [1]:
import cv2 as cv
import numpy as np

img = cv.imread('D:/OpenCV2/Assets/skincancer.png')

def trackbar(x):
    threshold_value = x
    max_value = 255
    _, threshold_img = cv.threshold(img, thresh=threshold_value, maxval=max_value, type=cv.THRESH_BINARY)
    cv.imshow('window', threshold_img)

cv.imshow('window', img)
cv.createTrackbar('threshold', 'window', 2, 255, trackbar)
cv.waitKey(0)
cv.destroyAllWindows()

## **1.2 Zero Thresholding**

Zero thresholding is simple as making the pixel values zero when they are under a certain threshold. It is also called zeroing

In [2]:
img = cv.imread('D:/OpenCV2/Assets/skincancer.png')

def trackbar(x):
    threshold_value = x
    max_value = 255
    _, threshold_img = cv.threshold(img, thresh=threshold_value, maxval=max_value, type=cv.THRESH_TOZERO)
    cv.imshow('window', threshold_img)

cv.imshow('window', img)
cv.createTrackbar('threshold', 'window', 2, 255, trackbar)
cv.waitKey(0)
cv.destroyAllWindows()

## **1.3 Adaptive Thresholding**

Adaptive thresholding is a technique in which the threshold value for seperating different parts of the image is determinted automatically by analyzing the surrounding local neighborhood pixels. 

The process of binarizing an image involves calculating the average value of the pixels in a particular region of the image. This average value is then used as a threshold to determine which pixels should be classified as background and which ones as foreground. Pixels with a density lower than the average threshold are classified as background, while those with a density higher than the threshold are classified as foreground.

In [7]:
img = cv.imread('D:/OpenCV2/Assets/skincancer.png')

gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

adaptive_threshold_img = cv.adaptiveThreshold(gray, maxValue = 255, adaptiveMethod=cv.ADAPTIVE_THRESH_MEAN_C, thresholdType=cv.THRESH_BINARY, blockSize=11, C = 2)

cv.imshow('window', adaptive_threshold_img)

cv.waitKey(0)
cv.destroyAllWindows()

## **1.4 2D Convolution**

Convolution is a widely used mathematical operation in image processing. It has various applications such as smoothing, feature extraction, blurring, and more. This operation requires a kernel which is undergone and operation called Convolution on each slides of pixels that of the same size as the kernel. Depending on the kernel used, different effects can be produced on the resulting image.

In [17]:
img = cv.imread('D:/OpenCV2/Assets/newton.jpg')

kernel = np.ones((5, 5), 'float32') / 25
print(kernel)

convolved_image = cv.filter2D(img, -1, kernel = kernel)

cv.imshow('window', convolved_image)

cv.waitKey(0)
cv.destroyAllWindows()


[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
